
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Reydel
 */
public class CANDIDATES_DETAILS extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form CANDIDATES_DETAILS
     */
    public CANDIDATES_DETAILS() {
        setUndecorated(true);
        conn = DBConnection.getConnection();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CANDIDATE_DETAILS = new javax.swing.JPanel();
        CANDIDATES_DETAILS_NAME = new javax.swing.JLabel();
        CANDIDATES_DETAILS_AGE = new javax.swing.JLabel();
        CANDIDATES_DETAILS_BIRTHDAY = new javax.swing.JLabel();
        CANDIDATES_DETAILS_CATEGORY = new javax.swing.JLabel();
        CANDIDATES_DETAILS_IMAGE = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CANDIDATE_DETAILS.setBackground(new java.awt.Color(204, 204, 255));
        CANDIDATE_DETAILS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CANDIDATES_DETAILS_NAME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CANDIDATES_DETAILS_NAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CANDIDATES_DETAILS_NAME.setText("name");
        CANDIDATE_DETAILS.add(CANDIDATES_DETAILS_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 240, 42));

        CANDIDATES_DETAILS_AGE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CANDIDATES_DETAILS_AGE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CANDIDATES_DETAILS_AGE.setText("age");
        CANDIDATE_DETAILS.add(CANDIDATES_DETAILS_AGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 240, 42));

        CANDIDATES_DETAILS_BIRTHDAY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CANDIDATES_DETAILS_BIRTHDAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CANDIDATES_DETAILS_BIRTHDAY.setText("birthday");
        CANDIDATE_DETAILS.add(CANDIDATES_DETAILS_BIRTHDAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 240, 42));

        CANDIDATES_DETAILS_CATEGORY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CANDIDATES_DETAILS_CATEGORY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CANDIDATES_DETAILS_CATEGORY.setText("category");
        CANDIDATE_DETAILS.add(CANDIDATES_DETAILS_CATEGORY, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 240, 42));

        CANDIDATES_DETAILS_IMAGE.setText("jLabel1");
        CANDIDATE_DETAILS.add(CANDIDATES_DETAILS_IMAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 350, 250));

        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        CANDIDATE_DETAILS.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CANDIDATE_DETAILS, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CANDIDATE_DETAILS, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CANDIDATES_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CANDIDATES_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CANDIDATES_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CANDIDATES_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CANDIDATES_DETAILS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CANDIDATES_DETAILS_AGE;
    private javax.swing.JLabel CANDIDATES_DETAILS_BIRTHDAY;
    private javax.swing.JLabel CANDIDATES_DETAILS_CATEGORY;
    private javax.swing.JLabel CANDIDATES_DETAILS_IMAGE;
    private javax.swing.JLabel CANDIDATES_DETAILS_NAME;
    private javax.swing.JPanel CANDIDATE_DETAILS;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    public void RETRIEVE_CANDIDATE(Integer ids) {
        try {

            if (ids != null) {
                String query = "SELECT name, age, birthday, category, image FROM candidate WHERE id = ?";
                pst = conn.prepareStatement(query);
                pst.setInt(1, ids);
                rs = pst.executeQuery();

                if (rs.next()) {
                    String name = rs.getString("name");
                    int age = rs.getInt("age");
                    Date birthday = rs.getDate("birthday");
                    String height = rs.getString("category");
                    byte[] imageData = rs.getBytes("image");

                    CANDIDATES_DETAILS_NAME.setText(name);
                    CANDIDATES_DETAILS_AGE.setText(String.valueOf(age));

                    SimpleDateFormat dateFormat = new SimpleDateFormat("MMMM d, yyyy");
                    String birthdayString = dateFormat.format(birthday);

                    CANDIDATES_DETAILS_BIRTHDAY.setText(birthdayString);
                    CANDIDATES_DETAILS_CATEGORY.setText(height);

//                    RETRIEVE IMAGE 
                    ImageIcon imageIcon = new ImageIcon(imageData);
                    Image scaledImage = imageIcon.getImage().getScaledInstance(CANDIDATES_DETAILS_IMAGE.getWidth(), CANDIDATES_DETAILS_IMAGE.getHeight(), Image.SCALE_SMOOTH);
                    CANDIDATES_DETAILS_IMAGE.setIcon(new ImageIcon(scaledImage));
                    CANDIDATES_DETAILS_IMAGE.setIcon(new ImageIcon(scaledImage));

                } else {
                    JOptionPane.showMessageDialog(null, "Candidate not found");
                }
            } else {

                JOptionPane.showMessageDialog(null, "Invalid ID");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
